name: kancil
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.1.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  rename: ^3.1.0
  mobile_scanner: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Noto_Sans/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
