name: kancil
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.1.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  rename: ^3.1.0
  barcode_scan2: ^4.5.1
  path_provider: ^2.0.15   # versi terbaru bisa dicek di pub.dev
  file_picker: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/iconapp.png
    - assets/logoapp.png
    - assets/fonts/Noto_Sans/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic-VariableFont_wdth,wght.ttf
          style: italic

flutter_icons:
  android: true
  image_path: "assets/iconapp.png"

flutter_native_splash:
  color: "#ffffff"        # Background splash
  image: assets/logoapp.png # Logo di tengah
  android: true
